### ISSUE TITLE
texte trop zoomé quand le display est scalé

### ISSUE THREAD

**Issue by GiovanniKarra** [Tfloow/UCLouvainDown#6]
![image](https://github.com/Tfloow/UCLouvainDown/assets/93490682/6fd81199-3bcc-41ca-a133-c31a83af3802)

**Comment by Tfloow** [comment]
Le début des problèmes ahah

**Comment by Tfloow** [comment]
J'ai essayé de reproduire le bug visuel sur windows sans succès. Je sais pas si c'est firefox sur linux ou gnome qui fait n'imp

**Comment by GiovanniKarra** [comment]
![image](https://github.com/Tfloow/UCLouvainDown/assets/93490682/c2110b04-b1b0-451c-b7ab-c4d9060e353c)

j'ai ça à 100% scale

**Comment by Tfloow** [comment]
J'ai fait des changements sur la façon dont le site est render (j'ai plus utilisé des `%` au lieu des `px`)

Dis moi si c'est mieux/réglé le souci

**Comment by Tfloow** [comment]
Je close l'issue car aucune nouvelle et j'ai fait une refonte du rendering qui devrait avoir corrigé ça
